from building import *

CWD = GetCurrentDir()

objs = Glob("*.c")


@register_library
class LibraryRingBufferV1(Library):
    def config(self):
        self.include = [CWD]
        self.CPPPATH = ["$INFRAS"]
        self.source = objs
